# Generated by Django 3.2.14 on 2022-07-15 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
