# Generated by Django 3.2.14 on 2022-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20220715_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="image",
            field=models.ImageField(
                default="", upload_to="media/account/images"
            ),
        ),
    ]
