# Generated by Django 3.2.14 on 2022-07-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_myuser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
