# Generated by Django 3.2.14 on 2022-07-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_myuser_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="approved",
            new_name="new_user",
        ),
    ]
