# Generated by Django 3.2.14 on 2022-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_rename_approved_myuser_new_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
