# Generated by Django 3.2.14 on 2022-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_myuser_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="new_user",
            field=models.BooleanField(default=True),
        ),
    ]
