# Generated by Django 3.2.14 on 2022-07-25 11:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220721_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='user_name', unique=True),
        ),
    ]
