# Generated by Django 4.0.6 on 2022-08-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_myuser_new_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="new_slug",
            new_name="slug",
        ),
    ]
