# Generated by Django 3.2.14 on 2022-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="new_request",
            field=models.BooleanField(default=True),
        ),
    ]
