# Generated by Django 3.2.14 on 2022-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_new_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="uploaded_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
