# Generated by Django 3.2.14 on 2022-07-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20220718_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="del_request",
            field=models.BooleanField(default=False),
        ),
    ]
