# Generated by Django 3.2.14 on 2022-07-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_blog_del_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="like",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="Like",
        ),
    ]
