# Generated by Django 3.2.14 on 2022-07-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20220719_1127"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="auther",
            new_name="blog_auther",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="content",
            new_name="blog_content",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="del_request",
            new_name="blog_del_request",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="image",
            new_name="blog_image",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="is_approved",
            new_name="blog_is_approved",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="new_request",
            new_name="blog_new_request",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="rating",
            new_name="blog_rating",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="title",
            new_name="blog_title",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="uploaded_on",
            new_name="blog_uploaded_on",
        ),
    ]
