# Generated by Django 3.2.14 on 2022-07-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_auto_20220721_0613"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="blog_comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="wblog",
            new_name="blog_key",
        ),
    ]
