# Generated by Django 3.2.14 on 2022-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20220721_0623"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="blog_add_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
