# Generated by Django 3.2.14 on 2022-07-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_rename_blog_add_on_comment_blog_added_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="blog_added_on",
            new_name="comment_added_on",
        ),
    ]
