# Generated by Django 3.2.14 on 2022-07-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_auto_20220721_0458"),
        ("blog", "0012_rename_blog_added_on_comment_comment_added_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_reply", models.TextField()),
                ("reply_added_on", models.DateTimeField(auto_now=True)),
                (
                    "comment_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.myuser",
                    ),
                ),
            ],
        ),
    ]
