# Generated by Django 3.2.14 on 2022-07-21 11:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="new_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="blog_title",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="new_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="blog_key",
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
