# Generated by Django 3.2.14 on 2022-07-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_blog_blog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="new_slug",
        ),
    ]
