# Generated by Django 3.2.14 on 2022-07-22 04:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comment_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
