# Generated by Django 3.2.14 on 2022-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_blog_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_content",
            field=models.TextField(null=True),
        ),
    ]
