# Generated by Django 3.2.14 on 2022-07-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_auto_20220722_0750"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="blog_discription",
            new_name="blog_description",
        ),
    ]
