# Generated by Django 3.2.14 on 2022-07-22 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_rename_blog_discription_blog_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
