# Generated by Django 3.2.14 on 2022-07-22 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_blog_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_content",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
