# Generated by Django 3.2.14 on 2022-07-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_search"),
    ]

    operations = [
        migrations.RenameField(
            model_name="search",
            old_name="i",
            new_name="object_blog",
        ),
    ]
