# Generated by Django 3.2.14 on 2022-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_search_search_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_content',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
