# Generated by Django 3.2.14 on 2022-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_alter_blog_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(
                default="blog/images/image.jpg",
                null=True,
                upload_to="blog/images",
            ),
        ),
    ]
